force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>The person who buys services of the company</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Project and Developer</description>
    <label>Project Assignment</label>
    <nameField>
        <label>Project Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ItCompanyServices.cls
public class ItCompanyServices{
    
   public static Database.SaveResult createProject(Id clientId){
     //create project
     Project__c project = new Project__c(Client__c = clientId, Name = 'New project from Database.SaveResult for client with ID: ' + clientId);
     Database.SaveResult srProject = Database.insert(project);
        
        if (srProject.isSuccess()){
        
        System.debug('Successfully inserted project. Project ID: ' + srProject.getId());
            
        } else {
             for(Database.Error err : srProject.getErrors()) {
            System.debug('The following error has occurred.');
            System.debug(err.getStatusCode() + ': ' + err.getMessage());
            System.debug('Project fields that affected this error: ' + err.getFields());
	        }
        }
        
        return srProject;
    
    }

    public static void createProjectAssignment(Id projectId, Id developerId){
    //create project assignment
      try {
	    Project_Assignment__c projectAssignment = new Project_Assignment__c(Name = 'PA-Test2', Developer__c = developerId, Project__c = projectId);
    	insert projectAssignment;
        System.debug(projectAssignment.Name + ' inserted Successfully');
    	} catch (DmlException e) {
    	System.debug('A DML exception has occurred: ' +e.getMessage());
    	}
    }

    


}