force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>The person who buys services of the company</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>client total budget</description>
    <label>Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Total_Active_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Projects__c</fullName>
    <defaultValue>0</defaultValue>
    <description>number of all active projects of this client</description>
    <label>Total Active Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Project and Developer</description>
    <label>Project Assignment</label>
    <nameField>
        <label>Project Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ItCompanyDAO.cls
public with sharing class ItCompanyDAO {

  public static Set<Id> getAvailableDeveloperIds() {

        List<Project_Assignment__c> availableDeveloperIds = new List<Project_Assignment__c>([
            SELECT Developer__c, Developer__r.Name 
            FROM Project_Assignment__c 
            WHERE Developer__r.Total_Billable_Projects__c < 5 
            OR Developer__r.Total_Billable_Projects__c = NULL //чи треба цю перевірку?
            ]);
      
      Set<Id> setId = new Set<Id>();
      
      for( Project_Assignment__c availableDeveloperId : availableDeveloperIds){
          setId.add(availableDeveloperId.Developer__c);
      }

        System.debug(setId);
        return setId;
    }

    public static Set<Id> getUnassignedDeveloperIds() {

       List<Developer__c> DevelopersIds = new List<Developer__c>([
            SELECT Id 
            FROM Developer__c 
            WHERE Total_Billable_Projects__c = 0  
            OR Total_Billable_Projects__c = NULL 
            ]);   
      
      Set<Id> setId = new Set<Id>();
      
      for( Developer__c DeveloperId : DevelopersIds){
          setId.add(DeveloperId.Id);
      }

        System.debug(setId);
        return setId;
}

public static List<Client__c> getClients(Integer limitNumber, Integer offsetNumber){

    List<Client__c> getClients = Database.query(
        'SELECT Name, Email__c, Total_Active_Projects__c, Budget__c '
        + 'FROM Client__c '
        + 'ORDER BY Name ASC '
        + 'LIMIT :limitNumber ' 
        + 'OFFSET :offsetNumber'
    );
    system.debug(getClients);
    return getClients;

}

}