force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>The person who buys services of the company</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Total_Active_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Projects__c</fullName>
    <defaultValue>0</defaultValue>
    <description>number of all active projects of this client</description>
    <label>Total Active Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <formula>IF(  (Total_Billable_Projects__c  &gt; 0),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmp&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBaTk&quot;, &quot;Green&quot;, 25, 25),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmu&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBZjK&quot;, &quot;Yellow&quot;, 25, 25)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Billable?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Budge__c.field-meta.xml
<CustomField>
    <fullName>Project_Budge__c</fullName>
    <description>project budge</description>
    <label>Project Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Project and Developer</description>
    <label>Project Assignment</label>
    <nameField>
        <label>Project Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ItCompanyDAOTest.cls
@isTest
public class ItCompanyDAOTest {
    
   @testSetup 
    static void dataSetup(){
        
  	Developer__c dev1 = new Developer__c(Name = 'Test Dev-1', Total_Billable_Projects__c = 1);
 	Developer__c dev2 = new Developer__c(Name = 'Test Dev-2', Total_Billable_Projects__c = 1);
  	Developer__c dev3 = new Developer__c(Name = 'Test Dev-3', Total_Billable_Projects__c = 0);
    insert new List<Developer__c>{dev1, dev2,dev3};
        
    Project__c pr1 = new Project__c(Name = 'Test Pr-1', Active__c = true, Is_Billable__c = true, Project_Budge__c = 111);
 	Project__c pr2 = new Project__c(Name = 'Test Pr-2', Active__c = true, Is_Billable__c = true, Project_Budge__c = 111);
  	Project__c pr3 = new Project__c(Name = 'Test Pr-3', Active__c = true, Is_Billable__c = false);
    insert new List<Project__c>{pr1, pr2,pr3};
        
    Client__c cl1 = new Client__c(Name = 'Test Cl-1', Total_Active_Projects__c = 0);
    Client__c cl2 = new Client__c(Name = 'Test Cl-2', Total_Active_Projects__c = 2);
    Client__c cl3 = new Client__c(Name = 'Test Cl-3', Total_Active_Projects__c = 1);
    insert new List<Client__c>{cl1, cl2,cl3};
    
    Project_Assignment__c pa1 = new Project_Assignment__c(Name = 'Test Pa-1', Developer__c = dev1.id, Project__c = pr1.id);
 	Project_Assignment__c pa2 = new Project_Assignment__c(Name = 'Test Pa-2', Developer__c = dev2.id, Project__c = pr2.id);
  	Project_Assignment__c pa3 = new Project_Assignment__c(Name = 'Test Pa-3', Developer__c = dev3.id, Project__c = pr3.id);
    insert new List<Project_Assignment__c>{pa1, pa2,pa3};
        
    }
    
    @isTest
    static void getAvailableDeveloperIdsTest(){
              
              
    Test.startTest();
        
    Set<Id> resultSet = ItCompanyDAO.getAvailableDeveloperIds();
        
    Test.stopTest();
        
    System.assertEquals(3, resultSet.size(), 'ItCompanyDAO.getAvailableDeveloperIds return the wrong amount of ID Set');
    }
    
    @isTest
    static void getUnassignedDeveloperIdsTest(){
               
    Test.startTest();
        
    Set<Id> resultSet = ItCompanyDAO.getUnassignedDeveloperIds();
        
    Test.stopTest();
        
    System.assertEquals(1, resultSet.size(), 'ItCompanyDAO.getUnassignedDeveloperIds return the wrong amount of ID Set');
        
    }
    
    @isTest
    static void getClientsTest(){
        Integer limitNumber = 2;
        Integer offsetNumber = 2;
                
    Test.startTest();
        
    List<Client__c> resultList = ItCompanyDAO.getClients(limitNumber,offsetNumber);
        
    Test.stopTest();
        
    System.assertEquals(1, resultList.size(), 'ItCompanyDAO.getClients return the wrong amount of Client__c List');
    }
    
    @isTest
    static void getDevelopersTest(){
        Integer limitNumber = 2;
        Integer offsetNumber = 2;
        Set<Id> developerId = new Set<Id>();
         List<Developer__c> devs = [SELECT Id,Name FROM Developer__c];
         for(Developer__c dev: devs){
          developerId.add(dev.id);}
        
     Test.startTest();
        
    List<Developer__c> resultList = ItCompanyDAO.getDevelopers(developerId,limitNumber,offsetNumber);
        
    Test.stopTest();
        
    System.assertEquals(1, resultList.size(), 'ItCompanyDAO.getDevelopers return the wrong amount of Developer__c List');
    
    }
    
    @isTest
    static void getClientTotalActiveProjectsTest(){
        
    Set<Id> clientIds = new Set<Id>();
    List<Client__c> clnts = [SELECT Id FROM Client__c];
    for(Client__c clnt: clnts){
    clientIds.add(clnt.id);}
   
    Test.startTest();
        
    Map<Id, Integer> resultMap = ItCompanyDAO.getClientTotalActiveProjects(clientIds);
        
    Test.stopTest();
        
    System.assertEquals(3, resultMap.size(), 'ItCompanyDAO.getClientTotalActiveProjects return the wrong amount of Client__c Map');
    System.assertEquals(0, resultMap.get(clnts[0].id), 'ItCompanyDAO.getClientTotalActiveProjects return the wrong amount of Client ClientTotalActiveProjects');
    System.assertEquals(1, resultMap.get(clnts[2].id), 'ItCompanyDAO.getClientTotalActiveProjects return the wrong amount of Client ClientTotalActiveProjects');
    }
    
    @isTest
    static void getDeveloperTotalBillableProjectsTest(){
    
    Set<Id> developerIds = new Set<Id>();
    List<Developer__c> devs = [SELECT Id,Name FROM Developer__c];
    for(Developer__c dev: devs){
    developerIds.add(dev.id);}
        
        Test.startTest();
        
    Map<Id, Integer> resultMap = ItCompanyDAO.getDeveloperTotalBillableProjects(developerIds);
        
    Test.stopTest();
        
    System.assertEquals(2, resultMap.size(), 'ItCompanyDAO.getDeveloperTotalBillableProjects return the wrong amount of Client__c Map');
    System.assertEquals(1, resultMap.get(devs[0].id), 'ItCompanyDAO.getDeveloperTotalBillableProjects return the wrong amount of Developer Total Billable Projects');
    System.assertEquals(1, resultMap.get(devs[1].id), 'ItCompanyDAO.getDeveloperTotalBillableProjects return the wrong amount of Developer Total Billable Projects');

    }
    
}