force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>The person who buys services of the company</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>client total budget</description>
    <label>Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Total_Active_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Projects__c</fullName>
    <defaultValue>0</defaultValue>
    <description>number of all active projects of this client</description>
    <label>Total Active Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MostProfitableClientsController.cls
public with sharing class MostProfitableClientsController {
    @AuraEnabled
    public static Client__c[] getMostProfitableClients(Integer limitNumber){
        
        return [SELECT id, Name, Total_Active_Projects__c, Budget__c
                FROM Client__c
                WHERE OwnerId=: UserInfo.getUserId() 
                AND Budget__c != null 
                ORDER BY Budget__c desc LIMIT :limitNumber];
    }

}