force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <formula>IF(  (Total_Billable_Projects__c  &gt; 0),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmp&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBaTk&quot;, &quot;Green&quot;, 25, 25),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmu&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBZjK&quot;, &quot;Yellow&quot;, 25, 25)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Billable?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Budge__c.field-meta.xml
<CustomField>
    <fullName>Project_Budge__c</fullName>
    <description>project budge</description>
    <label>Project Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Project and Developer</description>
    <label>Project Assignment</label>
    <nameField>
        <label>Project Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectAssignmentTriggerTest.cls
@isTest
public class ProjectAssignmentTriggerTest {
    
    @testSetup 
    static void dataSetup(){
        
  	Developer__c dev1 = new Developer__c(Name = 'Test Dev-1', Total_Billable_Projects__c = 0);
 	Developer__c dev2 = new Developer__c(Name = 'Test Dev-2', Total_Billable_Projects__c = 0);
  	Developer__c dev3 = new Developer__c(Name = 'Test Dev-3', Total_Billable_Projects__c = 0);
    insert new List<Developer__c>{dev1, dev2,dev3};
        
    Project__c pr1 = new Project__c(Name = 'Test Pr-1', Active__c = true, Is_Billable__c = true, Project_Budge__c = 111);
 	Project__c pr2 = new Project__c(Name = 'Test Pr-2', Active__c = true, Is_Billable__c = true, Project_Budge__c = 111);
  	Project__c pr3 = new Project__c(Name = 'Test Pr-3', Active__c = true, Is_Billable__c = false, Project_Budge__c = 111);
    insert new List<Project__c>{pr1, pr2,pr3};
    
    Project_Assignment__c pa1 = new Project_Assignment__c(Name = 'Test Pa-1', Developer__c = dev1.id, Project__c = pr1.id);
 	Project_Assignment__c pa2 = new Project_Assignment__c(Name = 'Test Pa-2', Developer__c = dev2.id, Project__c = pr2.id);
  	Project_Assignment__c pa3 = new Project_Assignment__c(Name = 'Test Pa-3', Developer__c = dev3.id, Project__c = pr3.id);
    insert new List<Project_Assignment__c>{pa1, pa2,pa3};
        
    }

    @isTest
    static void onBeforeInsertTest(){
        
    Developer__c dev2 = [SELECT Name FROM Developer__c WHERE Name = 'Test Dev-2'];
    Project__c pr1 = [SELECT Name FROM Project__c WHERE Name = 'Test Pr-1'];
    Project__c pr2 = [SELECT Name FROM Project__c WHERE Name = 'Test Pr-2'];
        
    List<Project_Assignment__c> newPas = new List<Project_Assignment__c>();
    Project_Assignment__c test1 = new Project_Assignment__c(Name = 'Test Pa-4', Developer__c = dev2.id, Project__c = pr1.id);
    newPas.add(test1);
    Project_Assignment__c test2 = new Project_Assignment__c(Name = 'Test Pa-5', Developer__c = dev2.id, Project__c = pr2.id);
    newPas.add(test2);
        
    Test.startTest();
        
   	Database.insert(newPas, false);
        
    Test.stopTest();
        
    List<Project_Assignment__c> test = ([SELECT Name FROM Project_Assignment__c]);
    //тест падає, бо отримуємо 4(було 3, додавали 2, один з яких з однаковими іменами, він не додався)
    //System.assertEquals(5, test.size(), 'ProjectAssignmentTriggerHandler.onBeforeInsert Project Assignment with same name of developer and project created.');
    System.assertEquals(4, test.size(), 'ProjectAssignmentTriggerHandler.onBeforeInsert Project Assignment with same name of developer and project weren\'t created.');
        
    }
    
    @isTest
    static void onAfterInsertTest(){
        
    List<Developer__c> developers = [SELECT Id FROM Developer__c]; 
    Project__c pr = [SELECT Id FROM Project__c WHERE Name = 'Test Pr-2'];
        
    Project_Assignment__c pa1 = new Project_Assignment__c(Name = 'Test Pa', Developer__c = developers[0].id, Project__c = pr.id);
    Project_Assignment__c pa2 = new Project_Assignment__c(Name = 'Test Pa', Developer__c = developers[2].id, Project__c = pr.id);
        
    Test.startTest();
        
    insert pa1;
    insert pa2;
        
    Test.stopTest();
         
    List<Project_Assignment__c> tests = ([SELECT Developer__c, Project__r.Is_Billable__c FROM Project_Assignment__c]);
    System.assertEquals(5, tests.size(), 'ProjectAssignmentTriggerHandler.onAfterInsert  new Project Assignments weren\'t created.');
        
    Developer__c dev = [SELECT Total_Billable_Projects__c FROM Developer__c WHERE Name = 'Test Dev-1'];
    System.assertEquals(true, dev.Total_Billable_Projects__c == 2);
        
    Developer__c devTest2 = [SELECT Total_Billable_Projects__c FROM Developer__c WHERE Name = 'Test Dev-3'];
    System.assertEquals(true, devTest2.Total_Billable_Projects__c == 1);
    }
  
}