force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <formula>IF(  (Total_Billable_Projects__c  &gt; 0),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmp&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBaTk&quot;, &quot;Green&quot;, 25, 25),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmu&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBZjK&quot;, &quot;Yellow&quot;, 25, 25)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Billable?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Project and Developer</description>
    <label>Project Assignment</label>
    <nameField>
        <label>Project Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectTriggerHandler.cls
public class ProjectTriggerHandler {
    
    public static void onAfterUpdate(Map<Id, Project__c> oldProjectsMap, List<Project__c> updatedProjects) {
    //Total Billable Projects of the Developer should be recalculated each time Is Billable field is changed on the Project
    List<Developer__c> developers = [
        SELECT Id, Total_Billable_Projects__c, (
        SELECT Id FROM Project_Assignments__r 
        )
        FROM Developer__c
        ];
         
        for (Project__c updatedProject : updatedProjects) {
        Project__c oldProject = oldProjectsMap.get(updatedProject.Id);
            if (oldProject.Is_Billable__c != updatedProject.Is_Billable__c) {
                for (Developer__c developer : developers) {
                	if(updatedProject.Is_Billable__c){
                    developer.Total_Billable_Projects__c += 1;
                    } else developer.Total_Billable_Projects__c -= 1;
                }
            }
        }
        
        update developers;
    }

}