force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <formula>IF(  (Total_Billable_Projects__c  &gt; 0),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmp&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBaTk&quot;, &quot;Green&quot;, 25, 25),
        IMAGE(&quot;https://sfschool5-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004wrmu&amp;operationContext=CHATTER&amp;contentId=05T7Q00000JBZjK&quot;, &quot;Yellow&quot;, 25, 25)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Billable?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Project and Developer</description>
    <label>Project Assignment</label>
    <nameField>
        <label>Project Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectAssignmentTriggerHandler.cls
public with sharing class ProjectAssignmentTriggerHandler {

   public static void onBeforeInsert(List<Project_Assignment__c> newPas) {
        List<Project_Assignment__c> oldPas = new List<Project_Assignment__c>([SELECT Developer__c, Project__c FROM Project_Assignment__c]);
            for(Project_Assignment__c oldPa : oldPas){
                for (Project_Assignment__c newPa : newPas){
                    if(newPa.Developer__c == oldPa.Developer__c && newPa.Project__c == oldPa.Project__c){
                    newPa.addError('A Project Assignmen with the same developer and project already exists');
                    }
                }
            }
    }

     //Total Billable Projects of the Developer should be recalculated each time a new Project Assignment is created
                                      //попробувати з нью мап
    public static void onAfterInsert(List<Project_Assignment__c> newPas) {

        Set<id> ProjectAssignment2Developer = new Set<id>();
   
        for (Project_Assignment__c newPa : newPas) {
            //тут вирішила перевірити чи проект Billable, бо якщо ні, то нам в сеті цей Id не потрібний
            if(newPa.Project__r.Is_Billable__c){
           ProjectAssignment2Developer.add(newPa.Developer__c);
            }
        }
        
        List<Developer__c> developers = [
                SELECT Id, Total_Billable_Projects__c
                FROM Developer__c
                WHERE Id IN :ProjectAssignment2Developer
        ];
        system.debug(developers);
        
        AggregateResult [] devs = [
            SELECT Developer__r.Id,
            COUNT(Developer__r.Total_Billable_Projects__c)
            FROM Project_Assignment__c
            WHERE Developer__r.Id IN :ProjectAssignment2Developer
            GROUP BY Developer__r.Id];
         system.debug(devs);
        
        for (Developer__c developer : developers) {
        for (AggregateResult dev : devs) {
            for (id devId : ProjectAssignment2Developer){
                if(ProjectAssignment2Developer.contains(dev.Id)){
                	if(devId == dev.Id){
                integer totalBillableProjects = integer.valueof(dev.get('expr0'));
                developer.Total_Billable_Projects__c = totalBillableProjects += 1;  
                	}  
            	}         
            }
        }
     }
                update developers;
        system.debug(developers);
        }

        public static void onAfterUpdate(Map<Id, Project_Assignment__c> oldAssignmentsMap, List<Project_Assignment__c> newAssignments) {
         //Total Billable Projects of the Developer should be recalculated each time Is Billable field is changed on the Project
         Set<id> devIds = new Set<id>();
         
          for (Project_Assignment__c newAssignment : newAssignments) {
           devIds.add(newAssignment.Developer__c);
            
        }
         
          List<Developer__c> developers = [
                SELECT Id, Total_Billable_Projects__c
                FROM Developer__c
                WHERE Id IN :devIds
        ];
            
             AggregateResult [] devs = [
            SELECT Developer__r.Id,
            COUNT(Developer__r.Total_Billable_Projects__c)
            FROM Project_Assignment__c
            WHERE Developer__r.Id IN :devIds
            GROUP BY Developer__r.Id];
         system.debug(devs);
         
        for (Project_Assignment__c newAssignment : newAssignments) {
            Project_Assignment__c oldAssignment = oldAssignmentsMap.get(newAssignment.Id);
        
            if (oldAssignment.Project__r.Is_Billable__c != newAssignment.Project__r.Is_Billable__c) {
                for(Developer__c developer:developers ){
                    for(AggregateResult dev:devs){
                    integer totalBillableProjects = integer.valueof(dev.get('expr0'));
                if(newAssignment.Project__r.Is_Billable__c){
                    developer.Total_Billable_Projects__c = totalBillableProjects += 1;
                } else  developer.Total_Billable_Projects__c = totalBillableProjects -= 1;
                }
            }
                
            }
        }
        
         update developers;
    }
    }